---
tiers:
    -
        name: onap-infra
        order: 1
        ci_loop: '(daily)|(weekly)'
        description: >-
            Set of basic k8s Functional tests to validate the ONAP installation.
        testcases:
            -
                case_name: onap-k8s
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    This test case verifies that the ONAP pods are all Running
                    and shows the pods, deployments, svc and events
                run:
                    name: 'onap_k8s'
            -
                case_name: onap-helm
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    This test case verifies that the ONAP charts are in
                    DEPLOYED status
                run:
                    name: 'onap-helm'
